#!/usr/bin/env bash
# Build the optional page-scrolling Newsboat used by newsboat-session.py.
set -euo pipefail
repo=$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)
build_dir="${XDG_CACHE_HOME:-$HOME/.cache}/newsboat-paged"
install_dir="$HOME/.local/lib/newsboat-paged"
mkdir -p "$build_dir" "$install_dir"
curl -fL https://github.com/newsboat/newsboat/archive/refs/tags/r2.44.tar.gz -o "$build_dir/source.tar.gz"
printf '%s  %s\n' aa3d144f737a39567100e82effd1dfd9a0dbcc705332ec66d0c35a750a9a3b10 "$build_dir/source.tar.gz" | sha256sum -c -
tar -xzf "$build_dir/source.tar.gz" -C "$build_dir"
cd "$build_dir/newsboat-r2.44"
patch -p1 < "$repo/newsboat/patches/paged-lists.patch"
patch -p1 < "$repo/newsboat/patches/download-status.patch"
patch -p1 < "$repo/newsboat/patches/live-queries.patch"
patch -p1 < "$repo/newsboat/patches/starred-badges.patch"
patch -p1 < "$repo/newsboat/patches/highlight-selection.patch"
patch -p1 < "$repo/newsboat/patches/all-sources.patch"
patch -p1 < "$repo/newsboat/patches/stable-badge-position.patch"
patch -p1 < "$repo/newsboat/patches/smooth-starred-entry.patch"
patch -p1 < "$repo/newsboat/patches/all-unread-count.patch"
patch -p1 < "$repo/newsboat/patches/all-unread-filter.patch"
patch -p1 < "$repo/newsboat/patches/instant-view-return.patch"
patch -p1 < "$repo/newsboat/patches/starred-total-count.patch"
patch -p1 < "$repo/newsboat/patches/downloads-total-count.patch"
patch -p1 < "$repo/newsboat/patches/live-list-removal.patch"
patch -p1 < "$repo/newsboat/patches/undo-actions.patch"
patch -p1 < "$repo/newsboat/patches/saved-list-row-numbers.patch"
patch -p1 < "$repo/newsboat/patches/watched-progress.patch"
patch -p1 < "$repo/newsboat/patches/platform-feed-icons.patch"
patch -p1 < "$repo/newsboat/patches/commentary-list.patch"
patch -p1 < "$repo/newsboat/patches/commentary-badges.patch"
patch -p1 < "$repo/newsboat/patches/commentary-undo.patch"
patch -p1 < "$repo/newsboat/patches/all-globe-icon.patch"
patch -p1 < "$repo/newsboat/patches/list-badge-order.patch"
patch -p1 < "$repo/newsboat/patches/download-search-read-items.patch"
patch -p1 < "$repo/newsboat/patches/refresh-total.patch"
patch -p1 < "$repo/newsboat/patches/refresh-any-list.patch"
patch -p1 < "$repo/newsboat/patches/refresh-summary.patch"
patch -p1 < "$repo/newsboat/patches/multi-action-undo.patch"
patch -p1 < "$repo/newsboat/patches/stable-download-delete-selection.patch"
patch -p1 < "$repo/newsboat/patches/download-watch-order.patch"
patch -p1 < "$repo/newsboat/patches/last-opened-marker.patch"
patch -p1 < "$repo/newsboat/patches/item-notes.patch"
patch -p1 < "$repo/newsboat/patches/stable-download-removal-order.patch"
patch -p1 < "$repo/newsboat/patches/video-only-watch-percentage.patch"
patch -p1 < "$repo/newsboat/patches/article-reading-progress.patch"
patch -p1 < "$repo/newsboat/patches/favorites-list.patch"
patch -p1 < "$repo/newsboat/patches/query-list-icons.patch"
patch -p1 < "$repo/newsboat/patches/feed-highlight-selection.patch"
patch -p1 < "$repo/newsboat/patches/favorites-title-heart.patch"
patch -p1 < "$repo/newsboat/patches/new-list-row-numbers.patch"
patch -p1 < "$repo/newsboat/patches/vods-list.patch"
patch -p1 < "$repo/newsboat/patches/random-starred.patch"
patch -p1 < "$repo/newsboat/patches/vod-download-progress.patch"
patch -p1 < "$repo/newsboat/patches/copy-url-shortcut.patch"
patch -p1 < "$repo/newsboat/patches/starred-reading-progress.patch"
patch -p1 < "$repo/newsboat/patches/starred-progress-order.patch"
patch -p1 < "$repo/newsboat/patches/visual-rows.patch"
patch -p1 < "$repo/newsboat/patches/search-source-names.patch"
patch -p1 < "$repo/newsboat/patches/resume-network-recovery.patch"
patch -p1 < "$repo/newsboat/patches/new-live-count.patch"
patch -p1 < "$repo/newsboat/patches/unique-links.patch"
patch -p1 < "$repo/newsboat/patches/pending-downloads-first.patch"
patch -p1 < "$repo/newsboat/patches/books-list.patch"
patch -p1 < "$repo/newsboat/patches/books-reading-progress.patch"
patch -p1 < "$repo/newsboat/patches/random-shortcut-footer.patch"
patch -p1 < "$repo/newsboat/patches/playlist-cache-import.patch"
patch -p1 < "$repo/newsboat/patches/playlist-loading-transition.patch"
patch -p1 < "$repo/newsboat/patches/playthroughs-list.patch"
patch -p1 < "$repo/newsboat/patches/playlist-thumbnails.patch"
patch -p1 < "$repo/newsboat/patches/refresh-ui-thread.patch"
patch -p1 < "$repo/newsboat/patches/home-shortcut.patch"
patch -p1 < "$repo/newsboat/patches/refresh-item-ui-thread.patch"
patch -p1 < "$repo/newsboat/patches/list-thumbnails.patch"
patch -p1 < "$repo/newsboat/patches/refresh-redraw-ui-thread.patch"
patch -p1 < "$repo/newsboat/patches/thumbnail-flow-layout.patch"
patch -p1 < "$repo/newsboat/patches/list-storage-totals.patch"
patch -p1 < "$repo/newsboat/patches/playlist-cover-thumbnails.patch"
patch -p1 < "$repo/newsboat/patches/action-spinner.patch"
patch -p1 < "$repo/newsboat/patches/download-pending-spinner.patch"
patch -p1 < "$repo/newsboat/patches/history-everywhere.patch"
patch -p1 < "$repo/newsboat/patches/playthrough-cover-thumbnails.patch"
patch -p1 < "$repo/newsboat/patches/read-mark-database-contention.patch"
patch -p1 < "$repo/newsboat/patches/visual-downloads.patch"
patch -p1 < "$repo/newsboat/patches/playlist-delete-undo.patch"
patch -p1 < "$repo/newsboat/patches/playthrough-progress-order.patch"
patch -p1 < "$repo/newsboat/patches/collection-visible-row-numbers.patch"
patch -p1 < "$repo/newsboat/patches/playlist-row-avatars.patch"
patch -p1 < "$repo/newsboat/patches/starred-progress-column.patch"
patch -p1 < "$repo/newsboat/patches/playlist-avatar-title-position.patch"
patch -p1 < "$repo/newsboat/patches/all-list-row-avatars.patch"
patch -p1 < "$repo/newsboat/patches/stable-active-download-order.patch"
patch -p1 < "$repo/newsboat/patches/title-hover.patch"
patch -p1 < "$repo/newsboat/patches/descriptive-undo.patch"
patch -p1 < "$repo/newsboat/patches/pinned-items.patch"
patch -p1 < "$repo/newsboat/patches/viewing-queue.patch"
patch -p1 < "$repo/newsboat/patches/collection-resume.patch"
patch -p1 < "$repo/newsboat/patches/queue-undo-shortcut.patch"
patch -p1 < "$repo/newsboat/patches/queue-remaining-time.patch"
patch -p1 < "$repo/newsboat/patches/queue-title-time.patch"
patch -p1 < "$repo/newsboat/patches/queue-compact-layout.patch"
patch -p1 < "$repo/newsboat/patches/queue-row-move.patch"
patch -p1 < "$repo/newsboat/patches/queue-bulk-move.patch"
patch -p1 < "$repo/newsboat/patches/queue-visual-yank.patch"
patch -p1 < "$repo/newsboat/patches/queue-title-panel.patch"
patch -p1 < "$repo/newsboat/patches/video-row-durations.patch"
patch -p1 < "$repo/newsboat/patches/queue-header-avatar.patch"
patch -p1 < "$repo/newsboat/patches/queue-header-compact-scroll.patch"
patch -p1 < "$repo/newsboat/patches/global-home-search.patch"
patch -p1 < "$repo/newsboat/patches/queue-stop-after.patch"
patch -p1 < "$repo/newsboat/patches/queue-snooze-header.patch"
patch -p1 < "$repo/newsboat/patches/aligned-badge-columns.patch"
patch -p1 < "$repo/newsboat/patches/thumbnail-zoom.patch"
patch -p1 < "$repo/newsboat/patches/timed-snooze.patch"
patch -p1 < "$repo/newsboat/patches/empty-new-mailbox.patch"
patch -p1 < "$repo/newsboat/patches/new-mailbox-glimmer.patch"
patch -p1 < "$repo/newsboat/patches/queue-time-indent.patch"
patch -p1 < "$repo/newsboat/patches/empty-new-title.patch"
patch -p1 < "$repo/newsboat/patches/selected-title-scroll.patch"
patch -p1 < "$repo/newsboat/patches/selected-title-scroll-activation.patch"
patch -p1 < "$repo/newsboat/patches/queue-title-hover.patch"
patch -p1 < "$repo/newsboat/patches/home-column-alignment.patch"
patch -p1 < "$repo/newsboat/patches/nonblocking-bulk-delete.patch"
patch -p1 < "$repo/newsboat/patches/timed-snooze-row.patch"
make -j"${NEWSBOAT_BUILD_JOBS:-4}" WARNFLAGS="-Werror -Wall -Wextra -Wunreachable-code -Wno-error=unused-function" newsboat
install -m 755 newsboat "$install_dir/newsboat.new"
mv "$install_dir/newsboat.new" "$install_dir/newsboat"
