# Save position on quit
# save-position-on-quit=yes
save-position-on-quit
watch-later-options=vid,aid,sid,volume,start,speed,sub-visibility
# write-filename-in-watch-later-config
write-filename-in-watch-later-config=yes

# Set total maximum cache size (e.g., 500 MiB)
# This will buffer both forwards and backwards
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=200MiB

force-seekable=yes

# Play video immediately before cache buffer is full
# this is important to ensure fast playback
cache-pause-initial=no

# Speed up the initial TLS handshake
tls-verify=no

# Set the maximum number of seconds of video to buffer ahead of the current position (e.g., 300 seconds or 5 minutes)
# This can help a lot with intermittent connections
# demuxer-readahead-secs=300
demuxer-readahead-secs=1
# Tell MPV to start the "demuxer" (the downloader) as soon as the URL is loaded
demuxer-thread=yes

# Enable caching
cache=yes

# Set cache size to 100MB (default is typically much lower)
# cache-default=102400
# cache=100m
# Alternatively, set cache size based on time (e.g., 60 seconds)
# cache-secs=10
cache-secs=300

# Need to set this otherwise going into fullscreen mode forces
# HDR mode seemingly and it freezes for a few seconds
vo=gpu-next
# vo=gpu

volume-max=300

sub-auto=no

# Allow communication from other programs to talk to MPV while it's running
# to allow clipping script etc.
input-ipc-server=/tmp/mpv-yt-ipc

# --- AMD Hardware Acceleration (The "Fan-Quiet" Settings) ---
# Use VA-API for AMD hardware decoding
# hwdec=vaapi
hwdec=auto-safe
# Vulkan is highly efficient on the Ryzen 7040 series
gpu-api=vulkan
# Performance profile to keep the GPU cool and fans low
profile=fast
# Explicitly use Wayland for Hyprland compatibility
# gpu-context=wayland
gpu-context=auto

# --- Scaling & Smoothness ---
# Uses efficient scaling to reduce power draw
scale=bilinear
cscale=bilinear
dscale=bilinear
# Smooths out motion without taxing the CPU
video-sync=display-resample
interpolation=yes
tscale=oversample

# --- Audio ---
# Keeps audio synced during speed changes or lag
audio-pitch-correction=yes

[memo-only-web-streams]
profile-cond=not (path:find("youtube.com") or path:find("youtu.be") or path:find("twitch.tv"))
profile-restore=copy-equal
script-opts-append=memo-enabled=no

ytdl-format=bestvideo[height<=?1080][vcodec^=vp9]+bestaudio/bestvideo[height<=?1080][vcodec!=av01]+bestaudio/best[height<=?1080]
ytdl-raw-options=cookies=~/my_cookies.txt,no-warnings=,no-playlist=

screenshot-directory=/home/knaught/pictures/screenshots/mpv
